//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('SpinWheelRewards')
export class SpinWheelRewardsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  rewardName: string;

  @Column('integer', { nullable: true })
  pointsValue: number;
}
