//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Users: [
      { username: 'username 1', email: 'email 1', pointsBalance: 1, id: 4 },
      { username: 'username 2', email: 'email 2', pointsBalance: 2, id: 65 },
      { username: 'username 3', email: 'email 3', pointsBalance: 3, id: 82 },
      { username: 'username 4', email: 'email 4', pointsBalance: 4, id: 90 },
      { username: 'username 5', email: 'email 5', pointsBalance: 5, id: 84 },
    ],
    Tasks: [
      {
        title: 'title 1',
        description: 'description 1',
        pointsReward: 1,
        id: 51,
      },
      {
        title: 'title 2',
        description: 'description 2',
        pointsReward: 2,
        id: 7,
      },
      {
        title: 'title 3',
        description: 'description 3',
        pointsReward: 3,
        id: 76,
      },
      {
        title: 'title 4',
        description: 'description 4',
        pointsReward: 4,
        id: 68,
      },
      {
        title: 'title 5',
        description: 'description 5',
        pointsReward: 5,
        id: 95,
      },
    ],
    SpinWheelRewards: [
      { rewardName: 'rewardName 1', pointsValue: 1, id: 9 },
      { rewardName: 'rewardName 2', pointsValue: 2, id: 46 },
      { rewardName: 'rewardName 3', pointsValue: 3, id: 59 },
      { rewardName: 'rewardName 4', pointsValue: 4, id: 34 },
      { rewardName: 'rewardName 5', pointsValue: 5, id: 42 },
    ],
  },
};
export default data;
