//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Users: {
      name: 'Users',
      fields: {
        username: 'Username',
        email: 'Email',
        pointsBalance: 'Points Balance',
        id: 'id',
      },
    },
    Tasks: {
      name: 'Tasks',
      fields: {
        title: 'Title',
        description: 'Description',
        pointsReward: 'Points Reward',
        id: 'id',
      },
    },
    SpinWheelRewards: {
      name: 'Spin Wheel Rewards',
      fields: {
        rewardName: 'Reward Name',
        pointsValue: 'Points Value',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Users: {
      name: 'Users (fr)',
      fields: {
        username: 'Username (fr)',
        email: 'Email (fr)',
        pointsBalance: 'Points Balance (fr)',
        id: 'id',
      },
    },
    Tasks: {
      name: 'Tasks (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        pointsReward: 'Points Reward (fr)',
        id: 'id',
      },
    },
    SpinWheelRewards: {
      name: 'Spin Wheel Rewards (fr)',
      fields: {
        rewardName: 'Reward Name (fr)',
        pointsValue: 'Points Value (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
